name: Development

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: clean
        args: --verbose
    
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --all-features --profile=coverage -Zunstable-options
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile'
        RUSTDOCFLAGS: '-Cpanic=abort'

    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --no-fail-fast --all-features --profile=coverage -Zunstable-options
    
    - id: coverage  
      uses: actions-rs/grcov@v0.1

    - name: Coveralls upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ steps.coverage.outputs.report }}

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Swatinem/rust-cache@v2
      
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
            
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-audit
      
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --target wasm32-unknown-unknown
          
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

