name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: trunk

      - name: Build (trunk)
        working-directory: './cofd/app/'
        run: |
          trunk build --release --public-url /cofd-pc-rs

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './cofd/app/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/release/cofd-pc
            
  # release-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: nightly
  #         override: true

  #     - name: Release build
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: build
  #         args: --release --all-features
          
  #     - name: Test
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #         args: --release --all-features
          
  #     - uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         prerelease: false
  #         files: |
  #           target/release/cofd-pc            